spring:
  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
    thymeleaf:
      cache: false

  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
    url: jdbc:h2:mem:jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show_sql: true
    properties:
      hibernate:
        #      ddl-auto: none
        ddl-auto: create-drop
        format_sql: true
        default_batch_fetch_size: 1000


#logging.level:
#  org.hibernate.SQL: debug
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

#decorator:
#  datasource:
#    p6spy:
#      enable-logging: true

server:
  port: 8090