spring:
  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
    thymeleaf:
      cache: false

  datasource:
#    url: jdbc:h2:tcp://localhost/~/jpashop
    url: jdbc:h2:mem:jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: create-drop
      properties:
        hibernate:
#          show_sql: true
          format_sql  : true

#logging.level:
#  org.hibernate.SQL: debug
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8090